##RheaKVStoreOptions
---
clusterName: rhea_benchmark

placementDriverOptions:
  fake: true

storeEngineOptions:
  storageType: PMem
  rocksDBOptions:
    fastSnapshot: true
    dbPath: rhea_benchmark_db
  pmemDBOptions:
    dbPath: /mnt/mem/rhea_benchmark_db
  raftDataPath: /mnt/mem/rhea_benchmark_raft_data
  raftRpcCoreThreads: 128
  serverAddress:
    ip: 127.0.0.1
    port: 18091
  commonNodeOptions:
    raftOptions:
      readOnlyOptions: ReadOnlyLeaseBased
  regionEngineOptionsList:
    - { regionId:  1,                      endKey: 80000000 }
    - { regionId:  2, startKey: 80000000,                   }

onlyLeaderRead: true

failoverRetries: 0
futureTimeoutMillis: 2000
useParallelKVExecutor: false

